// Full ABI for DealBlock contract
export const DEALBLOCK_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_safeSingleton", type: "address" },
      { internalType: "address", name: "_safeProxyFactory", type: "address" },
      { internalType: "address", name: "_fallbackHandler", type: "address" },
      { internalType: "address", name: "_admin", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ALREADY_APPROVED", type: "error" },
  { inputs: [], name: "ALREADY_COMPLETED", type: "error" },
  { inputs: [], name: "ALREADY_FUNDED", type: "error" },
  { inputs: [], name: "APPROVALS_PENDING", type: "error" },
  { inputs: [], name: "DUPLICATE_APPROVER", type: "error" },
  { inputs: [], name: "EDIT_LOCKED", type: "error" },
  { inputs: [], name: "FUNDED_MILESTONE_CANNOT_BE_REMOVED", type: "error" },
  { inputs: [], name: "INSUFFICIENT_ALLOWANCE", type: "error" },
  { inputs: [], name: "INSUFFICIENT_BALANCE", type: "error" },
  { inputs: [], name: "INVALID_AMOUNT", type: "error" },
  { inputs: [], name: "INVALID_DEADLINE", type: "error" },
  { inputs: [], name: "INVALID_MILESTONE", type: "error" },
  { inputs: [], name: "INVALID_PROJECT", type: "error" },
  { inputs: [], name: "INVALID_TASK", type: "error" },
  { inputs: [], name: "INVALID_TOKEN", type: "error" },
  { inputs: [], name: "MODULE_EXECUTION_FAILED", type: "error" },
  { inputs: [], name: "MODULE_NOT_ENABLED", type: "error" },
  { inputs: [], name: "NOT_ADMIN", type: "error" },
  { inputs: [], name: "NOT_APPROVED", type: "error" },
  { inputs: [], name: "NOT_APPROVER", type: "error" },
  { inputs: [], name: "NOT_AUTHORIZED", type: "error" },
  { inputs: [], name: "NOT_FUNDED", type: "error" },
  { inputs: [], name: "NOT_INITIATOR", type: "error" },
  { inputs: [], name: "NOT_IN_REVIEW", type: "error" },
  { inputs: [], name: "NOT_LAST_MILESTONE", type: "error" },
  { inputs: [], name: "NOT_PAYEE", type: "error" },
  { inputs: [], name: "NO_APPROVERS", type: "error" },
  { inputs: [], name: "PREVIOUS_MILESTONES_NOT_COMPLETE", type: "error" },
  { inputs: [], name: "PROJECT_INACTIVE", type: "error" },
  { inputs: [], name: "SAFE_TRANSACTION_FAILED", type: "error" },
  { inputs: [], name: "STATUS_INVAILD", type: "error" },
  { inputs: [], name: "TRANSFER_FAILED", type: "error" },
  { inputs: [], name: "ZERO_ADDRESS", type: "error" },
  {
    inputs: [{ internalType: "address", name: "module", type: "address" }],
    name: "__enableModuleOnSetup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "ending_At", type: "uint256" },
      { internalType: "string[]", name: "task_Titles", type: "string[]" },
      { internalType: "string[]", name: "task_Descriptions", type: "string[]" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address[]", name: "approvers", type: "address[]" },
    ],
    name: "add_Milestone",
    outputs: [{ internalType: "uint256", name: "milestone_Index", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "string[]", name: "task_Titles", type: "string[]" },
      { internalType: "string[]", name: "task_Descriptions", type: "string[]" },
    ],
    name: "add_Task",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "approve_Milestone",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "cancel_Milestone",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "complete_Milestone",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "project_Id", type: "uint256" }],
    name: "complete_Project",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "deposit_Assets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "fund_Milestone",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "fund_Release",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "getMilestone",
    outputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "starting_At", type: "uint256" },
      { internalType: "uint256", name: "ending_At", type: "uint256" },
      { internalType: "enum DB_Variables.Status", name: "status", type: "uint8" },
      { internalType: "uint256", name: "approversLen", type: "uint256" },
      { internalType: "bool", name: "edit_Locked", type: "bool" },
      { internalType: "address", name: "vault", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "payee", type: "address" },
      {
        components: [
          { internalType: "string", name: "title", type: "string" },
          { internalType: "string", name: "description", type: "string" },
        ],
        internalType: "struct DB_Variables.Task[]",
        name: "tasks",
        type: "tuple[]",
      },
      { internalType: "bool", name: "initializerApprovalRequired", type: "bool" },
      { internalType: "bool", name: "initializerHasApproved", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "project_Id", type: "uint256" }],
    name: "getProject",
    outputs: [
      { internalType: "address", name: "vault_Address", type: "address" },
      { internalType: "address", name: "initializer", type: "address" },
      { internalType: "address", name: "paid_To", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "bool", name: "completed", type: "bool" },
      { internalType: "uint256", name: "milestoneCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "uint256", name: "new_Ending_At", type: "uint256" },
    ],
    name: "increase_Deadline",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "payee", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "milestone_Ending_At", type: "uint256" },
      { internalType: "string", name: "project_Title", type: "string" },
      { internalType: "string", name: "project_Description", type: "string" },
      { internalType: "string[]", name: "task_Titles", type: "string[]" },
      { internalType: "string[]", name: "task_Descriptions", type: "string[]" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address[]", name: "approvers", type: "address[]" },
    ],
    name: "initialize_Project",
    outputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "address", name: "safe", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "mark_Milestone_For_Review",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "project_Id", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "withdraw_Assets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const ERC20_ABI = [
  {
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
] as const;